version: "3"
services:
  docker:
    image: "docker:dind"
    hostname: "docker"
    environment:
      - "DOCKER_TLS_CERTDIR=/certs"
    ports:
      - "2376:2376"
    privileged: true
    volumes:
      - "jenkins-docker-certs:/certs/client"
      - "jenkins-data:/var/jenkins_home"
    restart: "always"
    dns:
      - "9.9.9.9"
      - "1.1.1.1"
    command:
      - "--insecure-registry=nexus:8082"
  jenkins:
    build: "."
    hostname: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - "DOCKER_HOST=tcp://docker:2376"
      - "DOCKER_CERT_PATH=/certs/client"
      - "DOCKER_TLS_VERIFY=1"
    volumes:
      - "jenkins-docker-certs:/certs/client:ro"
      - "jenkins-data:/var/jenkins_home"
    dns:
      - "9.9.9.9"
      - "1.1.1.1"
    depends_on:
      - "docker"
  nexus:
    image: "sonatype/nexus3"
    hostname: "nexus"
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - "nexus-data:/nexus-data"
    dns:
      - "9.9.9.9"
      - "1.1.1.1"
volumes:
  jenkins-docker-certs: {}
  jenkins-data: {}
  nexus-data: {}
